Loqate/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Custom address fields which Postcode Anywhere should integrate with</description>
    <label>Address Integration</label>
    <nameField>
        <label>Address Integration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address Integrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Loqate/main/default/objects/PostcodeAnywhereAddresses__c/PostcodeAnywhereAddresses__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Postcode Anywhere Addresses</label>
</CustomObject>

Loqate/main/default/objects/PostcodeAnywhereAddresses__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Loqate/main/default/objects/PostcodeAnywhereFields__c/PostcodeAnywhereFields__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Postcode Anywhere Fields</label>
</CustomObject>

Loqate/main/default/objects/PostcodeAnywhereFields__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

Loqate/main/default/objects/PostcodeAnywhereFields__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Loqate/main/default/objects/PostcodeAnywhereSettings__c/PostcodeAnywhereSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Postcode Anywhere Settings</label>
</CustomObject>

Loqate/main/default/objects/PostcodeAnywhereSettings__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <inlineHelpText>Your Postcode Anywhere API Key suitable for internal web service transactions. It should be in the format AA11-AA11-AA11-AA11.</inlineHelpText>
    <label>Key</label>
    <length>19</length>
    <type>Text</type>
</CustomField>

Loqate/main/default/classes/TestCases.cls
@isTest 
private class TestCases {
    static testMethod void testSetup() {
        SetupController controller = new SetupController ();
        
        controller.getSettings();
        controller.getAddresses();
        controller.Save();
        
        controller.setCountryCodes('');
        controller.setCountryCodes('IRL,GBR');
        controller.setCountryCodes('GBR,IRL');
        controller.setCountryCodes('GBR');       
        controller.getCountryCodes();
        controller.Save();
        
        controller.NewAddress();   
            
        List<PostcodeAnywhereAddresses__c> testAddresses;
        testAddresses = [select id from PostcodeAnywhereAddresses__c where Name = 'Test'];
        if (!testAddresses.isEmpty())
            controller.addressToDelete = testAddresses[0].Id;
        controller.DeleteAddress();     
        
        PostcodeAnywhereAddresses__c testAddress = new PostcodeAnywhereAddresses__c(Name='Test', Object__c='Test');
        upsert testAddress;
        
        testAddresses = [select id from PostcodeAnywhereAddresses__c where Name = 'Test'];
        if (!testAddresses.isEmpty())
            controller.addressToDelete = testAddresses[0].Id;
        controller.DeleteAddress();     
        
        controller.Save();
    }
    
    static testMethod void testAddresses() {
        PostcodeAnywhereAddresses__c testAddress = new PostcodeAnywhereAddresses__c(Name='Test', Object__c='Test');
        PostcodeAnywhereFields__c testField = new PostcodeAnywhereFields__c(Name='Test.Test__c', Field__c='Test__c', Address__c='Test');
        
        insert testAddress;
        insert testField;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(testAddress);
        EditAddressExtension extension = new EditAddressExtension(sc);
        extension.getIsEdit();
        extension.EditMode();
        extension.getAllSObjects();
        extension.getFields();
        extension.NewField();
        extension.DeleteField();
        extension.Abort();
        extension.SaveEdit();
    }
    
    static testMethod void testFields() {
        PostcodeAnywhereAddresses__c testAddress = new PostcodeAnywhereAddresses__c(Name='Test', Object__c='Test');
        PostcodeAnywhereFields__c testField = new PostcodeAnywhereFields__c(Name='Test.Test__c', Field__c='Test__c', Address__c='Test');
        
        insert testAddress;
        insert testField;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(testField);
        EditAddressFieldExtension extension = new EditAddressFieldExtension(sc);
        extension.getObjectName();
        extension.getAllFields();
        extension.SaveEdit();
        extension.Abort();
    }
    
    static testMethod void testAddressExtension() {
        PostcodeAnywhereSettings__c testSettings = new PostcodeAnywhereSettings__c (Key__c='AA11-AA11-AA11-AA11');
        PostcodeAnywhereAddresses__c testAddress = new PostcodeAnywhereAddresses__c(Name='Test', Object__c='Account');
        PostcodeAnywhereFields__c testField = new PostcodeAnywhereFields__c(Name='Test.Name', Field__c='Name', Address__c='Test');
        
        insert testSettings;
        insert testAddress;
        insert testField;

        AddressExtension extension = new AddressExtension();
        extension.getKey();
        extension.getCountryCodes();
        extension.getCountryByIP();
        extension.setAddressName('Test');
        extension.getAddressName();
        
        Account testAccount = new Account(Name='Test');
        extension.setSubjectRecord(testAccount);
        extension.getSubjectRecord();
        
        extension.getSortedFields();
        extension.UpdateAddressFields();
    }
}