Loqate/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Custom address fields which Postcode Anywhere should integrate with</description>
    <label>Address Integration</label>
    <nameField>
        <label>Address Integration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address Integrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Loqate/main/default/objects/PostcodeAnywhereAddresses__c/PostcodeAnywhereAddresses__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Postcode Anywhere Addresses</label>
</CustomObject>

Loqate/main/default/objects/PostcodeAnywhereFields__c/PostcodeAnywhereFields__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Postcode Anywhere Fields</label>
</CustomObject>

Loqate/main/default/objects/PostcodeAnywhereFields__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

Loqate/main/default/classes/EditAddressExtension.cls
public class EditAddressExtension {
    private Map<string, PostcodeAnywhereFields__c> fieldsMap;
    private List<PostcodeAnywhereFields__c> fields;
    private PostcodeAnywhereAddresses__c address;
    private Map<string, Schema.SobjectType> allObjectTypes;
    private ApexPages.StandardController standardController;
    private boolean editMode = false;
    
    public string fieldToDelete {get;set;}
    
    public EditAddressExtension(ApexPages.StandardController controller) {
        standardController = controller;
        address = (PostcodeAnywhereAddresses__c)standardController.getRecord();
        fieldsMap = PostcodeAnywhereFields__c.getAll();
        FilterFields();
        allObjectTypes = Schema.getGlobalDescribe();
        
        system.debug(allObjectTypes.size());
        
        editMode = address == null || address.Id == null;
    }
    
    public boolean getIsEdit() {
        return editMode;
    }
    
    public PageReference EditMode() {
        editMode = true;
        return null;
    }
    
    public string getAllSObjects() {
        List<string> allObjectNames = new List<string>();
        
        for (Schema.SobjectType objectType : allObjectTypes.values())
            allObjectNames.add(objectType.getDescribe().getName());
        
        return JSON.serialize(allObjectNames);
    }
    
    public void FilterFields() {
        fields = new List<PostcodeAnywhereFields__c>();
        
        for (PostcodeAnywhereFields__c field : fieldsMap.values()) {
            if (field.Address__c == address.Name)
                fields.add(field);
        }
    }
    
    public List<PostcodeAnywhereFields__c> getFields() {
        return fields;
    }
    
    public PageReference NewField() {
        PageReference newFieldPage = Page.EditAddressField;
        newFieldPage.getParameters().put('address', address.Name);
        return newFieldPage;
    }
    
    public PageReference DeleteField() {
        system.debug(fieldToDelete);
        delete [select id from PostcodeAnywhereFields__c where id = :fieldToDelete];
        fieldsMap = PostcodeAnywhereFields__c.getAll();
        FilterFields();
        return null;
    }
    
    public PageReference Abort() {
        PageReference setupPage = Page.Management;
        return setupPage;
    }
    
    public PageReference SaveEdit() {
        if (address.Name.contains(' ')) {
            address.Name.addError('The Address Name cannont contain spaces');
            return null;
        }
        
        standardController.save();
        editMode = false;
        return null;
    }
}