Loqate/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Custom address fields which Postcode Anywhere should integrate with</description>
    <label>Address Integration</label>
    <nameField>
        <label>Address Integration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address Integrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Loqate/main/default/objects/PostcodeAnywhereAddresses__c/PostcodeAnywhereAddresses__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Postcode Anywhere Addresses</label>
</CustomObject>

Loqate/main/default/objects/PostcodeAnywhereAddresses__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Loqate/main/default/objects/PostcodeAnywhereFields__c/PostcodeAnywhereFields__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Postcode Anywhere Fields</label>
</CustomObject>

Loqate/main/default/objects/PostcodeAnywhereFields__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

Loqate/main/default/objects/PostcodeAnywhereSettings__c/PostcodeAnywhereSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Postcode Anywhere Settings</label>
</CustomObject>

Loqate/main/default/objects/PostcodeAnywhereSettings__c/fields/CustomFieldNumber__c.field-meta.xml
<CustomField>
    <fullName>CustomFieldNumber__c</fullName>
    <label>CustomFieldNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Loqate/main/default/classes/EditAddressFieldExtension.cls
public class EditAddressFieldExtension {
    private PostcodeAnywhereFields__c field;
    private PostcodeAnywhereAddresses__c address;
    Map<string,Schema.SObjectField> allFields;
    ApexPages.StandardController standardController;
    private integer fieldCount;
    
    public EditAddressFieldExtension(ApexPages.StandardController controller) {
        standardController = controller;
        field = (PostcodeAnywhereFields__c)controller.getRecord();
        fieldCount = PostcodeAnywhereFields__c.getAll().size();
        
        string addressName = field.Address__c;
        
        if (addressName == null)
            addressName = ApexPages.currentPage().getParameters().get('address');
        
        Map<string, PostcodeAnywhereAddresses__c> addresses = PostcodeAnywhereAddresses__c.getAll();
        
        for (PostcodeAnywhereAddresses__c a : addresses.values()) {
            if (a.Name == addressName) {
                address = a;
                break;
            }
        }
        
        if (address != null && address.Object__c != null) {
            Schema.SobjectType objectType = Schema.getGlobalDescribe().get(address.Object__c);
            
            if (objectType != null)
                allFields = objectType.getDescribe().fields.getMap();
        }
    }
    
    public string getObjectName() {
        if (address != null && address.Object__c != null)
            return address.Object__c;
        
        return '';
    }
    
    public string getAllFields() {
        List<string> fields = new List<string>();
        
        if (allFields == null) return '[]';
        
        for (Schema.SObjectField f : allFields.values())
            fields.add(f.getDescribe().getName());
        
        return JSON.serialize(fields);
    }
    
    private string MakeNewCustomFieldName() {
       string prefix = 'Custom_';
       integer suffixNumber = 1;
       
       PostcodeAnywhereSettings__c currentSettings = PostcodeAnywhereSettings__c.getOrgDefaults();
       
       if (currentSettings != null && currentSettings.CustomFieldNumber__c != null)
           suffixNumber = integer.valueOf(currentSettings.CustomFieldNumber__c) + 1;
       
       currentSettings.CustomFieldNumber__c = suffixNumber;
       update currentSettings;
       
       return prefix + string.valueOf(suffixNumber);
    }
    
    public PageReference SaveEdit() {
        if (field.Name == null)
            field.Name = MakeNewCustomFieldName();
        
        standardController.save();
        
        if (address != null && address.Object__c != null) {
            PageReference editAddressPage = Page.EditAddress;
            editAddressPage.getParameters().put('id', address.Id);   
            return editAddressPage;            
        }

        return ReturnAddress();
    }
    
    public PageReference Abort() {
        return ReturnAddress();
    }
    
    private PageReference ReturnAddress() {
        if (address != null && address.Object__c != null) {
            PageReference editAddressPage = Page.EditAddress;
            editAddressPage.getParameters().put('id', address.Id);   
            return editAddressPage;            
        }

        return Page.Management;
    }
}