Loqate/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Loqate/main/default/objects/Country__c/fields/ISO2_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO2_Code__c</fullName>
    <label>ISO2 Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Loqate/main/default/objects/Country__c/fields/ISO3_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO3_Code__c</fullName>
    <label>ISO3 Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Loqate/main/default/classes/loqPhoneController.cls
public with sharing class loqPhoneController {
    public loqPhoneController() {

    }
    @AuraEnabled(cacheable=true)
    public static List<Country__c> getCountryList() {
        return [
            SELECT Id, Name, ISO2_Code__c,ISO3_Code__c 
            FROM Country__c
        ];
    }

    @AuraEnabled
        public static String loqUpdatePhone(String validphone, String ObjectName, String ObjId, String mapStr )
        {
            try {
                sObject queryRecord;
                  queryRecord=Schema.getGlobalDescribe().get(ObjectName).newSObject(ObjId);
                  queryRecord.put(mapstr, validPhone);
                  Upsert queryRecord;
                      //Return Success Message
                      return 'Record Updated Successfully ::'+ObjId;
                
            } catch (Exception e) {
                System.debug(String.valueOf(e));
                      //Return Exception as String
                    return 'Unable to update record.\n Please try manually updating the phone.\n Error:'+String.valueOf(e);
            }

        }

        


}