Loqate/main/default/objects/PostcodeAnywhereCountries__c/PostcodeAnywhereCountries__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Postcode Anywhere Countries</label>
</CustomObject>

Loqate/main/default/objects/PostcodeAnywhereCountries__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <label>Index</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Loqate/main/default/classes/CountryIndex.cls
global class CountryIndex implements Comparable {

    public PostcodeAnywhereCountries__c Country;
    
    public CountryIndex(PostcodeAnywhereCountries__c country) {
        this.Country = country;
    }
    
    global Integer compareTo(Object compareTo) {
        CountryIndex compare = (CountryIndex)compareTo;
        
        if (this.Country.Index__c > compare.Country.Index__c)
            return 1;
        
        if (this.Country.Index__c < compare.Country.Index__c)
            return - 1;
        
        return 0;      
    }
}